name: ClickUp Comment Sync

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
      - development
      - homologation

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: log-github-event
        run: echo '${{ toJSON(github.event) }}'

      - name: log-infos
        run: |
          echo clickup secrets $CLICKUP_TOKEN $ASSIGNEE_ID
        env:
          CLICKUP_URL: https://api.clickup.com
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
          ASSIGNEE_ID: ${{ secrets.ASSIGNEE_ID }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_USER: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}